#include <iostream>
#include <fstream>
#include <string>

using namespace std;

int main() {
//    ofstream cout("../DiscreteMathematics/Turing/aplusb.out");
    ofstream cout("aplusb.out");
    cout << "start: s\n"
            "accept: ac\n"
            "reject: rj\n"
            "blank: _\n"
            "\n"
            "s 0 -> s 3 >\n"
            "s 1 -> s 4 >\n"
            "s + -> End0 + >\n"
            "\n"
            "End0 0 -> End0 0 >\n"
            "End0 1 -> End0 1 >\n"
            "End0 _ -> Take0 _ <\n"
            "End0 + -> End0 + >\n"
            "\n"
            "End1 0 -> End1 0 >\n"
            "End1 1 -> End1 1 >\n"
            "End1 _ -> Take1 _ <\n"
            "End1 + -> End1 + >\n"
            "\n"
            "Take0 0 -> Add00 _ <\n"
            "Take0 1 -> Add01 _ <\n"
            "Take0 + -> St0 _ <\n"
            "\n"
            "Take1 0 -> Add10 _ <\n"
            "Take1 1 -> Add11 _ <\n"
            "Take1 + -> St1 _ <\n"
            "\n"
            "St0 0 -> St0 0 <\n"
            "St0 1 -> St0 1 <\n"
            "St0 3 -> St0 0 <\n"
            "St0 4 -> St0 1 <\n"
            "St0 _ -> ac _ >\n"
            "\n"
            "St1 0 -> St1 0 <\n"
            "St1 1 -> St1 1 <\n"
            "St1 3 -> St0 1 <\n"
            "St1 4 -> St1 0 <\n"
            "St1 _ -> ac 1 ^\n"
            "\n"
            "Add00 0 -> Add00 0 <\n"
            "Add00 1 -> Add00 1 <\n"
            "Add00 3 -> End0 0 >\n"
            "Add00 4 -> End0 1 >\n"
            "Add00 + -> Add00 + <\n"
            "Add00 _ -> End0 0 >\n"
            "\n"
            "Add01 0 -> Add01 0 <\n"
            "Add01 1 -> Add01 1 <\n"
            "Add01 3 -> End0 1 >\n"
            "Add01 4 -> End1 0 >\n"
            "Add01 + -> Add01 + <\n"
            "Add01 _ -> End0 1 >\n"
            "\n"
            "Add10 0 -> Add10 0 <\n"
            "Add10 1 -> Add10 1 <\n"
            "Add10 3 -> End0 1 >\n"
            "Add10 4 -> End1 0 >\n"
            "Add10 + -> Add10 + <\n"
            "Add10 _ -> End0 1 >\n"
            "\n"
            "Add11 0 -> Add11 0 <\n"
            "Add11 1 -> Add11 1 <\n"
            "Add11 3 -> End1 0 >\n"
            "Add11 4 -> End1 1 >\n"
            "Add11 + -> Add11 + <\n"
            "Add11 _ -> End1 0 >";
    return 0;
}