#include <iostream>
#include <fstream>
#include <string>

using namespace std;

int main() {
//    ofstream cout("../DiscreteMathematics/Turing/multiplication.out");
    ofstream cout("multiplication.out");
    cout << "start: s\n"
            "accept: ac\n"
            "reject: rj\n"
            "blank: _\n"
            "\n"
            "s 0 -> Set# 3 <\n"
            "s 1 -> Set# 4 <\n"
            "s 3 -> s 3 >\n"
            "s 4 -> s 4 >\n"
            "s * -> Set# & <\n"
            "s & -> s & >\n"
            "s # -> s # >\n"
            "s _ -> Set+ _ <\n"
            "\n"
            "Set# 3 -> Set# 3 <\n"
            "Set# 4 -> Set# 4 <\n"
            "Set# & -> Set# & <\n"
            "Set# # -> Set# # <\n"
            "Set# _ -> s # >\n"
            "\n"
            "Set+ 3 -> Set+ 3 <\n"
            "Set+ 4 -> Set+ 4 <\n"
            "Set+ & -> Set+ & <\n"
            "Set+ # -> Set+ # <\n"
            "Set+ _ -> Set0 + <\n"
            "\n"
            "Set0 # -> GetS 0 >\n"
            "Set0 _ -> GetS 0 >\n"
            "\n"
            "GetS 3 -> Set+0 # <\n"
            "GetS 4 -> Set+1 # <\n"
            "GetS & -> End & >\n"
            "GetS + -> GetS + >\n"
            "GetS # -> GetS # >\n"
            "\n"
            "Set+0 0 -> Set0 0 >\n"
            "Set+0 1 -> Set0 1 >\n"
            "Set+0 3 -> Set+0 3 <\n"
            "Set+0 4 -> Set+0 4 <\n"
            "Set+0 & -> Set+0 & <\n"
            "Set+0 + -> Set0 + >\n"
            "Set+0 # -> Set+0 # <\n"
            "\n"
            "Set+1 0 -> Set1 0 >\n"
            "Set+1 1 -> Set1 1 >\n"
            "Set+1 3 -> Set+1 3 <\n"
            "Set+1 4 -> Set+1 4 <\n"
            "Set+1 & -> Set+1 & <\n"
            "Set+1 + -> Set1 + >\n"
            "Set+1 # -> Set+1 # <\n"
            "\n"
            "Set1 # -> GetS 1 >\n"
            "\n"
            "End 3 -> End 3 >\n"
            "End 4 -> End 4 >\n"
            "End & -> End & >\n"
            "End # -> End # >\n"
            "End _ -> If _ <\n"
            "\n"
            "If 3 -> Set+0 _ <\n"
            "If 4 -> Add 3 <\n"
            "If & -> Del+ _ <\n"
            "\n"
            "Add 0 -> Add 0 <\n"
            "Add 1 -> Add 1 <\n"
            "Add 3 -> Add 3 <\n"
            "Add 4 -> Add 4 <\n"
            "Add + -> Add + <\n"
            "Add & -> Add & <\n"
            "Add # -> Add # <\n"
            "Add _ -> AddS _ >\n"
            "\n"
            "AddS 0 -> AddS 3 >\n"
            "AddS 1 -> AddS 4 >\n"
            "AddS + -> End0 + >\n"
            "\n"
            "End0 0 -> End0 0 >\n"
            "End0 1 -> End0 1 >\n"
            "End0 # -> Take0 # <\n"
            "End0 3 -> Take0 3 <\n"
            "End0 4 -> Take0 4 <\n"
            "End0 + -> End0 + >\n"
            "\n"
            "End1 0 -> End1 0 >\n"
            "End1 1 -> End1 1 >\n"
            "End1 # -> Take1 # <\n"
            "End1 3 -> Take1 3 <\n"
            "End1 4 -> Take1 4 <\n"
            "End1 + -> End1 + >\n"
            "\n"
            "Take0 0 -> Add00 3 <\n"
            "Take0 1 -> Add01 4 <\n"
            "Take0 + -> St0 + <\n"
            "\n"
            "Take1 0 -> Add10 3 <\n"
            "Take1 1 -> Add11 4 <\n"
            "Take1 + -> St1 + <\n"
            "\n"
            "St0 0 -> St0 0 <\n"
            "St0 1 -> St0 1 <\n"
            "St0 3 -> St0 0 <\n"
            "St0 4 -> St0 1 <\n"
            "St0 _ -> Go+ _ >\n"
            "\n"
            "St1 0 -> St1 0 <\n"
            "St1 1 -> St1 1 <\n"
            "St1 3 -> St0 1 <\n"
            "St1 4 -> St1 0 <\n"
            "St1 _ -> Go+ 1 >\n"
            "\n"
            "Add00 0 -> Add00 0 <\n"
            "Add00 1 -> Add00 1 <\n"
            "Add00 3 -> End0 0 >\n"
            "Add00 4 -> End0 1 >\n"
            "Add00 + -> Add00 + <\n"
            "Add00 _ -> End0 0 >\n"
            "\n"
            "Add01 0 -> Add01 0 <\n"
            "Add01 1 -> Add01 1 <\n"
            "Add01 3 -> End0 1 >\n"
            "Add01 4 -> End1 0 >\n"
            "Add01 + -> Add01 + <\n"
            "Add01 _ -> End0 1 >\n"
            "\n"
            "Add10 0 -> Add10 0 <\n"
            "Add10 1 -> Add10 1 <\n"
            "Add10 3 -> End0 1 >\n"
            "Add10 4 -> End1 0 >\n"
            "Add10 + -> Add10 + <\n"
            "Add10 _ -> End0 1 >\n"
            "\n"
            "Add11 0 -> Add11 0 <\n"
            "Add11 1 -> Add11 1 <\n"
            "Add11 3 -> End1 0 >\n"
            "Add11 4 -> End1 1 >\n"
            "Add11 + -> Add11 + <\n"
            "Add11 _ -> End1 0 >\n"
            "\n"
            "Go+ 0 -> Go+ 0 >\n"
            "Go+ 1 -> Go+ 1 >\n"
            "Go+ + -> Chg + >\n"
            "\n"
            "Chg 3 -> Chg 0 >\n"
            "Chg 4 -> Chg 1 >\n"
            "Chg # -> End # >\n"
            "\n"
            "Del+ 0 -> Del+ _ <\n"
            "Del+ 1 -> Del+ _ <\n"
            "Del+ 3 -> Del+ _ <\n"
            "Del+ 4 -> Del+ _ <\n"
            "Del+ # -> Del+ _ <\n"
            "Del+ + -> GoStart _ <\n"
            "\n"
            "GoStart 0 -> GoStart 0 <\n"
            "GoStart 1 -> GoStart 1 <\n"
            "GoStart _ -> ac _ >";
    return 0;
}